ASP.NET MVC/ShopVitrin/ShopVitrin/Models/ErrorViewModel.cs
namespace ShopVitrin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET MVC/ShopVitrin/ShopVitrin/Models/Urun.cs
namespace ShopVitrin.Models
{
    public class Urun
    {
        public int UrunId { get; set; }
        public string Isim { get; set; } = null!;
        public string? Aciklama { get; set; }
        public string? Resim { get; set; } = "Picture/kulaklık.png"; //default
    }
}

ASP.NET MVC/ShopVitrin/ShopVitrin/Models/UrunContext.cs
using Microsoft.EntityFrameworkCore;

namespace ShopVitrin.Models
{
    public class UrunContext : DbContext
    {
        public virtual DbSet<Urun> Urunler { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.\SQLEXPRESS;Database=ShopVitrin;Trusted_Connection=True;Trust Server Certificate=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            DummyData(modelBuilder);
            base.OnModelCreating(modelBuilder);
        }

        private void DummyData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Urun>().HasData(
                new Urun { UrunId = 1, Isim = "Erkek Beyaz Pantolon", Aciklama = "Donate: If yose conp pay for theour support.", Resim = "Picture/erkek_beyaz_pantolon.png" },
                new Urun { UrunId = 2, Isim = "Erkek Gri Ayakkabı", Aciklama = "ciated - click here to donate using PayPal. Thank you for your support.", Resim = "Picture/erkek_gri_ayakkabı.png" },
                new Urun { UrunId = 3, Isim = "Erkek Gri Pantolon", Aciklama = "Donate: If you use this siting PayPal. Thank you for your support.", Resim = "Picture/erkek_gri_pantolon.png" },
                new Urun { UrunId = 4, Isim = "Erkek Kareli Pantolon", Aciklama = "Donat. Thank you for your support.", Resim = "Picture/erkek_kareli_pantolon.png" },
                new Urun { UrunId = 5, Isim = "Erkek Mavi Hırka", Aciklama = "o donate using PayPal. Thank you for your support.", Resim = "Picture//erkek_mavi_hırka.png" },
                new Urun { UrunId = 6, Isim = "Erkek Tsirt", Aciklama = "Donate: If yated - click here toyour support.", Resim = "Picture/erkek_tsirt.png" },
                new Urun { UrunId = 7, Isim = "Erkek Tsirt Kırmızı", Aciklama = "Donate: If yu for your support.", Resim = "Picture/erkek_tsirt_kırmızı.png" },
                new Urun { UrunId = 8, Isim = "Kadın Çanta Takım", Aciklama = "Do. Thank you for your support.", Resim = "Picture/kadın_çanta_takım.png" },
                new Urun { UrunId = 9, Isim = "Kadın Kot Pantolon", Aciklama = "Donate: If you use this site regular pport.", Resim = "Picture/kadın_kot_pantolon.png" },
                new Urun { UrunId = 10, Isim = "Kadın Kot Siyah", Aciklama = "Donate: click here to donate using PayPal. Thank you for your support.", Resim = "Picture/kadın_kot_siyah.png" },
                new Urun { UrunId = 11, Isim = "Kadın Turuncu Hırka", Aciklama = "Dona your support.", Resim = "Picture/kadın_turuncu_hırka.png" },
                new Urun { UrunId = 12, Isim = "Kulaklık", Aciklama = "Donate:  hany sum is appreciated - click here to donate using PayPal. Thank you for your support.", Resim = "Picture/kulaklık.png" }
                 );
        }
    }
}

ASP.NET MVC/ShopVitrin/ShopVitrin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShopVitrin.Models;
using System.Diagnostics;

namespace ShopVitrin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET MVC/ShopVitrin/ShopVitrin/Controllers/UrunController.cs
using Microsoft.AspNetCore.Mvc;
using ShopVitrin.Models;

namespace ShopVitrin.Controllers
{
    public class UrunController : Controller
    {
        public static UrunContext _db = new UrunContext();

        public IActionResult Index()
        {
            List<Urun> urunler = _db.Urunler.ToList();
            return View(urunler);
        }

        [HttpPost]
        public IActionResult Index(int id)
        {
            List<Urun> urunler = _db.Urunler.ToList();
            var eklenecekUrun = urunler.FirstOrDefault(u => u.UrunId == id);
            if (eklenecekUrun != null)
            {
                Urun urun = new()
                {
                    Isim = eklenecekUrun.Isim,
                    Resim = eklenecekUrun.Resim,
                    Aciklama = eklenecekUrun.Aciklama
                };
                _db.Urunler.Add(urun);
                _db.SaveChanges();
            }
            return View("Index", _db.Urunler.ToList());
        }

        public IActionResult UrunGuncelle(int id)
        {
            List<Urun> urunler = _db.Urunler.ToList();
            var guncellenecekUrun = urunler.FirstOrDefault(u => u.UrunId == id);
            return View(guncellenecekUrun);
        }

        [HttpPost]
        public IActionResult UrunGuncelle(int id, string isim, string aciklama, IFormFile resim)
        {
            List<Urun> urunler = _db.Urunler.ToList();
            var guncellenecekUrun = urunler.FirstOrDefault(u => u.UrunId == id);
            guncellenecekUrun.Isim = isim ?? guncellenecekUrun.Isim;
            guncellenecekUrun.Aciklama = aciklama ?? guncellenecekUrun.Aciklama;
            if (resim != null && resim.Length > 0)
            {
                var dosyaYolu = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Picture", resim.FileName);

                using (var dosyaStream = new FileStream(dosyaYolu, FileMode.Create))
                {
                    resim.CopyTo(dosyaStream);
                }

                guncellenecekUrun.Resim = "/Picture/" + resim.FileName;
            }
            _db.SaveChanges();
            // Kayıt işlemi tamamlandıktan sonra, ilgili bir sonraki sayfaya yönlendirilebilirsiniz.
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UrunEkle(int id)
        {
            List<Urun> urunler = _db.Urunler.ToList();
            var eklenecekUrun = urunler.FirstOrDefault(u => u.UrunId == id);
            if (eklenecekUrun != null)
            {
                Urun urun = new()
                {
                    Isim = eklenecekUrun.Isim,
                    Resim = eklenecekUrun.Resim,
                    Aciklama = eklenecekUrun.Aciklama
                };
                _db.Urunler.Add(urun);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UrunSil(int id)
        {
            List<Urun> urunler = _db.Urunler.ToList();
            var silinecekUrun = urunler.FirstOrDefault(u => u.UrunId == id);
            if (silinecekUrun != null)
            {
                _db.Urunler.Remove(silinecekUrun);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ASP.NET MVC/ShopVitrin/ShopVitrin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}


<div class="text-center">
    <h1 class="display-4">ShopVitrin'e <abbr class="text-black-50">hoşgeldin</abbr> </h1>
    <p>ShopVitrin en güzel ürünlerini görmek için <a href="./Urun">TIKLA</a> </p>
</div>

ASP.NET MVC/ShopVitrin/ShopVitrin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopVitrin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopVitrin.styles.css" asp-append-version="true" />
</head>
<body class=" bg-dark bg-gradient bg-opacity-50">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid"> 
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopVitrin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Urun" asp-action="Index">Urunler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">    
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ShopVitrin - <a asp-area="" asp-controller="Urun" asp-action="Index">Urunlerimiz</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET MVC/ShopVitrin/ShopVitrin/Views/Urun/Index.cshtml
@model List<Urun>
@{
    ViewBag.Title = "Urunler";
}



<div class="pb-2 container-fluid bg-warning bg-gradient text-secondary">
    <h1 class="text-center">@ViewBag.Title</h1>

</div>

<div class="row ps-5 mt-3">
    @foreach (var item in Model)
    {
        <div class="card col-6" style="width: 18rem;">
            <img class="card-img-top" src="@item.Resim" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@item.Isim</h5>
                <p class="card-text">@item.Aciklama</p>
            </div>
            <div class="card-body">

                <form class="shadow-lg row" action="Urun" method="post">
                    <input type="hidden" name="id" value="@item.UrunId" />
                    <button id="@item.UrunId" type="submit" asp-action="UrunEkle" asp-controller="Urun" class="btn-success col-12">Ekle</button>
                    <input type="hidden" name="id" value="@item.UrunId" />
                    <button id="@item.UrunId" type="submit" asp-action="UrunGuncelle" asp-controller="Urun" formmethod="get" class="btn-warning col-6">Güncelle</button>
                    <input type="hidden" name="id" value="@item.UrunId" />
                    <button id="@item.UrunId" type="submit" asp-action="UrunSil" asp-controller="Urun" class="btn-danger col-6">Sil</button>
                </form>
            </div>
        </div>
    }
</div>

ASP.NET MVC/ShopVitrin/ShopVitrin/Views/Urun/UrunGuncelle.cshtml
@model Urun
<h1>Burası güncelleme sayfası</h1>
<form method="post" enctype="multipart/form-data">
    <input class="form-control" type="hidden" name="id" value="@Model.UrunId" />
    <input class="form-control" type="text" name="isim" value="@Model.Isim" />
    <input class="form-control" type="text" name="aciklama" value="@Model.Aciklama" />
    <input class="form-control-file" type="file" name="resim" value="@Model.Resim" />
    <button class="btn-warning" type="submit" asp-controller="Urun" asp-action="UrunGuncelle">Güncellemeyi Tamamla</button>
</form>